spring:
  application:
    name: ${APP_NAME}
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/
      database: ${DB_NAME}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}

rabbit:
  queue-name: ${QUEUE_NAME}
  exchange-name: ${EXCHANGE_NAME}
  routing-key: ${ROUTING_KEY}

server:
  port: ${PORT}